mtype: "DDPG"
variant: "simple"
dqnet: [400,300]
policynet: [400,300]
skip_frames_sync: 200
skip_frames_backward: 1
skip_policy_update: 2
buffer_size: 100000
begin_noise: 0.35
end_noise: 0.15
target_smooth: True
target_noise: 0.01
actor_lr: 0.0002
critic_lr: 0.0002
weight_decay: 0.001
episode: 5000