mtype: "DDPG"
variant: "simple"
dqnet: [400,300]
policynet: [400,300]
skip_frames_sync: 100
skip_frames_backward: 1
skip_policy_update: 2
buffer_size: 100000
begin_noise: 0.45
end_noise: 0.15
actor_lr: 0.0001
critic_lr: 0.001
weight_decay: 0.01
